version: "3"
services:
  django:
    build:
      context: .
      dockerfile: Backend/helloMovies/Dockerfile
    ports:
      - "8000:8000"

  react:
    build:
      context: .
      dockerfile: Frontend/HelloFoods/Dockerfile
    ports:
      - "3000:3000"
