# Generated by Django 4.2.6 on 2023-10-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('director', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating', models.CharField(max_length=10)),
                ('overview', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('actors', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
