name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Navigate to React Project
        run: cd Frontend/HelloMovies

      - name: Install dependencies
        run: pip install -r Backend/helloMovies/requirements.txt

      - name: Run tests
        working-directory: Backend/helloMovies
        run: python manage.py test
